options:
  port:
    type: int
    default: 80
    description: |
      Apache listen port
  host:
    type: string
    default: "*"
    description: |
      Adress on which Apache will listen. To listen on any interface, set "*".

